name: Github actions OIDC-GCP
on:
  push:
    branches: 
      - searce-workflow

jobs:
  deploy:
    name: Deploy
    uses: searce-shikhar/nested-workflow/.github/workflows/main.yml@main
    with:
      ecr_repository: shikhar-test