name: Github actions OIDC-GCP
on:
  push:
    branches: 
      - searce-workflow

jobs:
  deploy:
    name: Deploy
    uses: searce-shikhar/github-actions-deploy/.github/workflows/main.yml@v1
    with:
      ecr_repository: shikhar-test